feign:
    client:
        config:
            default:
                connectTimeout: 10000
                decoder: zswag.java.rest.feign.FeignZserioDecoder
                encoder: zswag.java.rest.feign.FeignZserioEncoder
                loggerLevel: basic
                readTimeout: 10000
    url: localhost:5000

logging:
    file:
        name: ./logs/${spring.application.name}.log
    level:
        root: WARN
        zswag: INFO

spring:
    application:
        name: zswag-zserio-calculator-client

    main:
        web-application-type: reactive

    messages:
        encoding: UTF-8 
        fallback-to-system-locale: true 

    mvc:
        async:
            request-timeout: -1
