feign:
    client:
        config:
            default:
                connectTimeout: 10000
                decoder: zswag.java.rest.openapi.client.FeignOpenApiDecoder
                encoder: zswag.java.rest.openapi.client.FeignOpenApiEncoder
                loggerLevel: basic
                readTimeout: 10000
    url: localhost:5000

logging:
    level:
        root: WARN
        zswag: INFO

spring:
    application:
        name: zswag-zserio-calculator-openapi-client

    main:
        web-application-type: reactive

    messages:
        encoding: UTF-8 
        fallback-to-system-locale: true 

    mvc:
        async:
            request-timeout: -1
